version: "3"
services:
  test-website:
    container_name: test-website
    build:
      context: test-website
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./test-website/src:/var/www
  website-tracker:
    container_name: website-tracker
    build:
      context: website-tracker
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./website-tracker:/var/www
  db:
    image: postgres
    container_name: pg-docker
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres/pixel:/var/lib/postgresql/data
  fake-sqs:
    container_name: fake-sqs
    image: s12v/elasticmq
    ports:
      - "9324:9324"
