version: "3"
services:
  test-website:
    container_name: test-website
    build:
      context: test-website
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./test-website/src:/var/www
  browser-magic-pixel:
    image: kyma/docker-nginx
    container_name: browser-magic-pixel
    restart: "always"
    ports:
      - "8081:80"
    volumes:
      - ./services/magic-pixel/build/index.js:/var/www/magic-pixel.js
  browser-event-tracker:
    image: kyma/docker-nginx
    container_name: browser-event-tracker
    restart: "always"
    ports:
      - "8082:80"
    volumes:
      - ./services/event-tracker/browser/app/scribe/scribe-analytics-debug.js:/var/www/scribe-analytics-debug.js
      - ./services/event-tracker/browser/app/build/index.js:/var/www/mp-event-tracker.js
#  browser-page-identification:
#    image: kyma/docker-nginx
#    container_name: browser-page-identification
#    restart: "always"
#    ports:
#      - "8083:80"
#    volumes:
#      - ./browser/page-identification/build/index.js:/var/www/mp-page-identification.js
#  browser-content-page-identification:
#    image: kyma/docker-nginx
#    container_name: browser-content-page-identification
#    restart: "always"
#    ports:
#      - "8084:80"
#    volumes:
#      - ./browser/content-identification/build/index.js:/var/www/mp-content-identification.js
  events-db:
    image: postgres
    container_name: pg-events-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres/event-db:/var/lib/postgresql/data
#  page-identification-db:
#    image: postgres
#    container_name: pg-page-identification-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: password
#    ports:
#      - 5433:5432
#    volumes:
#      - $HOME/docker/volumes/postgres/page-identification-db:/var/lib/postgresql/data
#  content-identification-db:
#    image: postgres
#    container_name: pg-content-identification-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: password
#    ports:
#      - 5434:5432
#    volumes:
#      - $HOME/docker/volumes/postgres/content-identification-db:/var/lib/postgresql/data
  fake-sqs:
    container_name: fake-sqs
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./config/elasticmq.conf:/opt/elasticmq.conf
