"""adds fingerprint table

Revision ID: 763e460bce3c
Revises: d34ba7ae70bb
Create Date: 2021-12-09 13:41:56.406662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "763e460bce3c"
down_revision = "d34ba7ae70bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fingerprint",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=True,
        ),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], name="fingerprint_person_id_fkey"
        ),
    )

    op.create_index(
        op.f("ix_fingerprint_person_id"), "fingerprint", ["person_id"], unique=False
    )


def downgrade():
    op.drop_index(op.f("ix_fingerprint_person_id"), table_name="fingerprint")
    op.drop_constraint("fingerprint_person_id_fkey", "fingerprint")
    op.drop_table("fingerprint")
