service: magicPixel

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  region: us-east-1
  tracing:
    apiGateway: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - arn:aws:s3:::${self:custom.magicPixelBucket}/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        - Fn::GetAtt:
            - EventQueue
            - Arn
  environment:
    NODE_ENV: 'test'
    ENV: ${opt:stage, 'local'}
    EVENT_QUEUE_NAME: ${self:custom.eventQueueName}
    SECRET_KEY: ${self:custom.flaskSecretKey}
    POSTGRES_USER: ${self:custom.postgres.${opt:stage, 'dev'}.user}
    POSTGRES_PW: ${self:custom.postgres.${opt:stage, 'dev'}.pw}
    POSTGRES_URL: ${self:custom.postgres.${opt:stage, 'dev'}.url}
    POSTGRES_DB: ${self:custom.postgres.${opt:stage, 'dev'}.db}
    MAGIC_PIXEL_BUCKET: ${self:custom.magicPixelBucket}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-finch
  - serverless-offline-sqs
  - serverless-offline

custom:
  magicPixelBucket: ${opt:stage, 'dev'}-magic-pixel
  eventQueueName: ${opt:stage, 'dev'}-event-queue
  eventBrowserQueueName: ${opt:stage, 'dev'}-event-browser-queue
  eventDocumentQueueName: ${opt:stage, 'dev'}-event-document-queue
  eventFormQueueName: ${opt:stage, 'dev'}-event-form-queue
  eventLocaleQueueName: ${opt:stage, 'dev'}-event-locale-queue
  eventSourceQueueName: ${opt:stage, 'dev'}-event-source-queue
  eventTargetQueueName: ${opt:stage, 'dev'}-event-target-queue
  flaskSecretKey: 'c0cbf5992af08ede97e11a3e'
  postgres:
    local:
      user: 'postgres'
      pw: 'docker'
      url: 'localhost'
      db: 'postgres'
    dev:
      user: 'root'
      pw: 'password'
      url: 'url'
      db: 'db'
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python
    pythonRequirements:
      dockerizePip: "non-linux"
  serverless-offline:
    httpPort: 5000
  serverless-offline-sqs:
    autoCreate: false                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - package.json
    - package-lock.json
    - README.md

  include:
    - magic_pixel/**

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: "/{proxy+}"
          method: ANY
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 86400
  sendEvent:
    handler: lambdas.send_event
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /send-event
          method: post
  consumeEvent:
    handler: lambdas.consume_event
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventQueue
              - Arn

resources:
  Resources:
    EventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.eventQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - EventDLQueue
              - Arn
    EventDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.eventQueueName}-deadletter
        MessageRetentionPeriod: 604800