service: magicPixel

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  region: us-east-1
  tracing:
    apiGateway: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - arn:aws:s3:::${self:custom.s3.magicPixelBucket}/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        - Fn::GetAtt:
            - EventQueue
            - Arn
  environment:
    NODE_ENV: 'test'
    ENV: ${opt:stage, 'local'}
    REACT_APP_AUTH0_CUSTOM_DOMAIN: ${self:custom.auth0.customDomain}
    REACT_APP_AUTH0_DB: ${self:custom.auth0.db.connection.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_API_URL: ${self:custom.auth0.api.url.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_CLIENT_ID: ${self:custom.auth0.app.clientId.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_CLIENT_SECRET: ${self:custom.auth0.app.clientSecret.${opt:stage, 'dev'}}
    REACT_APP_S3_TRACKER: ${self:custom.s3.magicPixelTracker}
    AUTH0_CUSTOM_DOMAIN: ${self:custom.auth0.customDomain}
    AUTH0_MGMT_DOMAIN: ${self:custom.auth0.mgmtDomain}
    AUTH0_DB: ${self:custom.auth0.db.connection.${opt:stage, 'dev'}}
    AUTH0_API_URL: ${self:custom.auth0.api.url.${opt:stage, 'dev'}}
    AUTH0_API_CLIENT_ID: ${self:custom.auth0.api.clientId}
    AUTH0_API_CLIENT_SECRET: ${self:custom.auth0.api.clientSecret}
    AUTH0_APP_CLIENT_ID: ${self:custom.auth0.app.clientId.${opt:stage, 'dev'}}
    SQS_REGION: ${self:custom.sqs.region}
    SQS_ENDPOINT_URL: ${self:custom.sqs.endpointUrl}
    SQS_EVENT_QUEUE_NAME: ${self:custom.sqs.eventQueueName}
    SECRET_KEY: ${self:custom.flask.secretKey}
    POSTGRES_USER: ${self:custom.postgres.${opt:stage, 'dev'}.user}
    POSTGRES_PW: ${self:custom.postgres.${opt:stage, 'dev'}.pw}
    POSTGRES_URL: ${self:custom.postgres.${opt:stage, 'dev'}.url}
    POSTGRES_DB: ${self:custom.postgres.${opt:stage, 'dev'}.db}
    MAGIC_PIXEL_BUCKET: ${self:custom.s3.magicPixelBucket}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-finch
  - serverless-offline-sqs
  - serverless-offline

custom:
  auth0:
    mgmtDomain: "dev-rvsp8waa.us.auth0.com"
    customDomain: "dev-rvsp8waa.us.auth0.com"
    app:
      clientId:
        dev: "VVGfoJXe1Fa4mYZLbQSi0yNh37L5hyRe"
        production: ""
      clientSecret:
        dev: "VqF9cqMQLafbUp7iKtW3YjEUD6Fyr9dEyY52JNU544jvj0DrmvCmiaQa3SO3zppi"
        production: ""
    api:
      clientId: "oZEsfWNP8SoFjQH2lBBbvJpAdcdGIIud"
      clientSecret: "es349JQUA6HUOeJuAhGna7nmUvMwzYnqsCrqpIW__qKuuuYNn0iKe1GNFVHAnTqp"
      url:
        dev: "https://magic-pixel.dev-api.com"
        production: ""
    db:
      connection:
        dev: "mp-dev-db"
        production: ""
  client:
    bucketName: magic-pixel-static
    distributionFolder: static
  flask:
    secretKey: 'c0cbf5992af08ede97e11a3e'
  s3:
    magicPixelBucket: ${opt:stage, 'dev'}-magic-pixel
    magicPixelTracker: ''
  sqs:
    region: 'us-east-1'
    endpointUrl: ''
    eventQueueName: ${opt:stage, 'dev'}-event-queue
  postgres:
    local:
      user: 'postgres'
      pw: 'docker'
      url: 'localhost'
      db: 'postgres'
    dev:
      user: 'root'
      pw: 'password'
      url: 'url'
      db: 'db'
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python
    pythonRequirements:
      dockerizePip: "non-linux"
  serverless-offline:
    httpPort: 5000
  serverless-offline-sqs:
    autoCreate: false                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - static/**
    - client/**
    - package.json
    - package-lock.json
    - .pytest_cache/**
    - README.md

  include:
    - magic_pixel/**

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    memorySize: 512
#    vpc:
#      securityGroupIds:
#        - sg-0ca7e29791a26efe7 # lambda sg
#      subnetIds:
#        - subnet-01d66241214a2f8f0
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: "/{proxy+}"
          method: ANY
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 86400
  sendEvent:
    handler: lambdas.send_event
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /send-event
          method: post
  consumeEvent:
    handler: lambdas.consume_event
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventQueue
              - Arn
  authentication:
    handler: lambdas.authentication
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /authentication
          method: post

resources:
  Resources:
    EventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - EventDLQueue
              - Arn
    EventDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventQueueName}-deadletter
        MessageRetentionPeriod: 604800
