"""adds alias table

Revision ID: a016a16f2341
Revises: d34ba7ae70bb
Create Date: 2021-12-27 06:02:27.971079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a016a16f2341"
down_revision = "d34ba7ae70bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=True,
        ),
        sa.Column("distinct_person_id", sa.Text(), nullable=False),
        sa.Column("visitor_uuid", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f('ix_alias_distinct_person_id'), 'alias', ['distinct_person_id'], unique=False)
    op.create_index(op.f('ix_alias_visitor_uuid'), 'alias', ['visitor_uuid'], unique=False)


def downgrade():
    op.drop_index(op.f('ix_alias_visitor_uuid'), table_name='alias')
    op.drop_index(op.f('ix_alias_distinct_person_id'), table_name='alias')
    op.drop_table("alias")
