service: magic-pixel-fe

framework: '2'

provider:
  name: aws
  region: us-east-1
  versionFunctions: false

plugins:
  - serverless-finch

custom:
  client:
    bucketName: magic-pixel-fe-${opt:stage}
    distributionFolder: build
    manageResources: false
    uploadOrder:
      - .*
      - index\.html
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: no-cache

resources:
  Resources:
    FEBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: magic-pixel-fe-${opt:stage}
        AccessControl: Private
        VersioningConfiguration:
          Status: Suspended
    FEBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FEBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: '*'
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: FEBucket
                    - /*
