## Pull nginx base image
#FROM kyma/docker-nginx
#
## Copy static assets into var/www
#COPY ./scribe/scribe-analytics.js /var/www/scribe-analytics.js
#COPY ./build/index.js /var/www/mp-tracker.js
#
## Start up nginx server
#CMD ["nginx"]
