service: magicPixel

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.9
  versionFunctions: false
  region: us-east-1
  tracing:
    apiGateway: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - arn:aws:s3:::${self:custom.s3.magicPixelBucket}/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        - Fn::GetAtt:
            - EventQueue
            - Arn
        - Fn::GetAtt:
            - EventIdentityQueue
            - Arn
        - Fn::GetAtt:
            - PageIdentificationQueue
            - Arn
        - Fn::GetAtt:
            - ContentIdentificationQueue
            - Arn
  environment:
    NODE_ENV: 'test'
    ENV: ${opt:stage, 'local'}
    REACT_APP_AUTH0_CUSTOM_DOMAIN: ${self:custom.auth0.customDomain}
    REACT_APP_AUTH0_DB: ${self:custom.auth0.db.connection.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_API_URL: ${self:custom.auth0.api.url.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_CLIENT_ID: ${self:custom.auth0.app.clientId.${opt:stage, 'dev'}}
    REACT_APP_AUTH0_CLIENT_SECRET: ${self:custom.auth0.app.clientSecret.${opt:stage, 'dev'}}
    REACT_APP_S3_TRACKER: ${self:custom.s3.magicPixelTracker}
    AUTH0_CUSTOM_DOMAIN: ${self:custom.auth0.customDomain}
    AUTH0_MGMT_DOMAIN: ${self:custom.auth0.mgmtDomain}
    AUTH0_DB: ${self:custom.auth0.db.connection.${opt:stage, 'dev'}}
    AUTH0_API_URL: ${self:custom.auth0.api.url.${opt:stage, 'dev'}}
    AUTH0_API_CLIENT_ID: ${self:custom.auth0.api.clientId}
    AUTH0_API_CLIENT_SECRET: ${self:custom.auth0.api.clientSecret}
    AUTH0_APP_CLIENT_ID: ${self:custom.auth0.app.clientId.${opt:stage, 'dev'}}
    SQS_REGION: ${self:custom.sqs.region}
    SQS_ENDPOINT_URL: ${self:custom.sqs.endpointUrl}
    SQS_EVENT_QUEUE_NAME: ${self:custom.sqs.eventQueueName}
    SQS_EVENT_IDENTITY_QUEUE_NAME: ${self:custom.sqs.eventIdentityQueueName}
    SQS_PAGE_IDENTIFICATION_QUEUE_NAME: ${self:custom.sqs.pageIdentificationQueueName}
    SQS_CONTENT_IDENTIFICATION_QUEUE_NAME: ${self:custom.sqs.contentIdentificationQueueName}
    SECRET_KEY: ${self:custom.flask.secretKey}
    POSTGRES_USER: ${self:custom.postgres.${opt:stage, 'dev'}.user}
    POSTGRES_PW: ${self:custom.postgres.${opt:stage, 'dev'}.pw}
    POSTGRES_URL: ${self:custom.postgres.${opt:stage, 'dev'}.url}
    POSTGRES_DB: ${self:custom.postgres.${opt:stage, 'dev'}.db}
    MAGIC_PIXEL_BUCKET: ${self:custom.s3.magicPixelBucket}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-finch
  - serverless-offline-sqs
  - serverless-offline

custom:
  auth0:
    mgmtDomain: "dev-rvsp8waa.us.auth0.com"
    customDomain: "dev-rvsp8waa.us.auth0.com"
    app:
      clientId:
        dev: "VVGfoJXe1Fa4mYZLbQSi0yNh37L5hyRe"
        production: ""
      clientSecret:
        dev: "VqF9cqMQLafbUp7iKtW3YjEUD6Fyr9dEyY52JNU544jvj0DrmvCmiaQa3SO3zppi"
        production: ""
    api:
      clientId: "oZEsfWNP8SoFjQH2lBBbvJpAdcdGIIud"
      clientSecret: "es349JQUA6HUOeJuAhGna7nmUvMwzYnqsCrqpIW__qKuuuYNn0iKe1GNFVHAnTqp"
      url:
        dev: "https://magic-pixel.dev-api.com"
        production: ""
    db:
      connection:
        dev: "mp-dev-db"
        production: ""
  client:
    bucketName: magic-pixel-static
    distributionFolder: static
  flask:
    secretKey: 'c0cbf5992af08ede97e11a3e'
  s3:
    magicPixelBucket: ${opt:stage, 'dev'}-magic-pixel
    magicPixelTracker: ''
  sqs:
    region: 'us-east-1'
    endpointUrl: ''
    eventQueueName: ${opt:stage, 'dev'}-event-queue
    eventIdentityQueueName: ${opt:stage, 'dev'}-event-identity-queue
    pageIdentificationQueueName: ${opt:stage, 'dev'}-page-identification-queue
    contentIdentificationQueueName: ${opt:stage, 'dev'}-content-identification-queue
  postgres:
    local:
      user: 'postgres'
      pw: 'docker'
      url: 'localhost'
      db: 'postgres'
    dev:
      user: 'root'
      pw: 'password'
      url: 'url'
      db: 'db'
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: python
    pythonRequirements:
      dockerizePip: "non-linux"
  serverless-offline:
    httpPort: 5000
  serverless-offline-sqs:
    autoCreate: false                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


package:
  exclude:
    - node_modules/**
    - venv/**
    - .venv/**
    - static/**
    - client/**
    - package.json
    - package-lock.json
    - .pytest_cache/**
    - README.md

  include:
    - content-identification/**

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    memorySize: 512
#    vpc:
#      securityGroupIds:
#        - sg-0ca7e29791a26efe7 # lambda sg
#      subnetIds:
#        - subnet-01d66241214a2f8f0
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: "/{proxy+}"
          method: ANY
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 86400
  authentication:
    handler: ./lambdas/authentication.authentication
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /authentication
          method: post
  identify-page:
    handler: ./lambdas/page_identification.identify_page
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: identification/page
          method: post
  page-identification:
    handler: ./lambdas/page_identification.page_identification
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PageIdentificationQueue
              - Arn
  identify-content:
    handler: ./lambdas/content_identification.identify_content
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: identification/content
          method: post
  content-identification:
    handler: ./lambdas/content_identification.content_identification
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ContentIdentificationQueue
              - Arn
  event-collection:
    handler: ./lambdas/events.event_collection
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: event/collection
          method: post
  event-ingestion:
    handler: ./lambdas/events.event_ingestion
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventQueue
              - Arn
  event-identity:
    handler: ./lambdas/events.event_identity
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventIdentityQueue
              - Arn

resources:
  Resources:
    EventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - EventDLQueue
              - Arn
    EventDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventQueueName}-deadletter
        MessageRetentionPeriod: 604800
    EventIdentityQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventIdentityQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - EventIdentityDLQueue
              - Arn
    EventIdentityDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.eventIdentityQueueName}-deadletter
        MessageRetentionPeriod: 604800
    PageIdentificationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.pageIdentificationQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - PageIdentificationQueueDLQueue
              - Arn
    PageIdentificationQueueDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.pageIdentificationQueueName}-deadletter
        MessageRetentionPeriod: 604800
    ContentIdentificationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.contentIdentificationQueueName}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 5
          deadLetterTargetArn:
            Fn::GetAtt:
              - ContentIdentificationQueueDLQueue
              - Arn
    ContentIdentificationQueueDLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs.contentIdentificationQueueName}-deadletter
        MessageRetentionPeriod: 604800