export const PAGE_ID_PROPERTIES = {
  eCommerce: {
    isEcommPage: false,
    keywords: [
      'paypal',
      'google_pay',
      'apple_pay',
      'bolt_pay',
      'stripe_for',
      'braintree_form',
      'square_form',
      'checkout',
      'purchase',
      'order',
      'buy',
      'order_summary',
      'total',
      'subtotal',
      'shipping',
      'tax',
      'payment',
      'promo_code',
      'coupon',
      'shipping_address',
      'billing_address',
    ],
    dom: {
      paypal: false,
      google_pay: false,
      apple_pay: false,
      bolt_pay: false,
      stripe_for: false,
      braintree_form: false,
      square_form: false,
      checkout: false,
      purchase: false,
      order: false,
      buy: false,
      order_summary: false,
      total: false,
      subtotal: false,
      shipping: false,
      tax: false,
      payment: false,
      promo_code: false,
      coupon: false,
      shipping_address: false,
      billing_address: false,
    },
    url: {
      checkout: false,
      purchase: false,
      order: false,
      buy: false,
      order_summary: false,
    },
  },
  confirmation: {
    keywords: ['thankyou', 'order', 'ordersummary', 'confirmation'],
    url: {
      thank_you: false,
      order_summary: false,
      order: false,
      confirmation: false,
    },
    dom: {
      confirmation: false,
    },
  },
  lead_gen: {
    keywords: ['email'],
    dom: {
      email: true,
    },
  },
  contact_us: {
    keywords: ['contact', 'feedback'],
    url: {
      contact: false,
      feedback: false,
    },
  },
  careers: {
    keywords: ['careers', 'jobs'],
    url: {
      careers: false,
      jobs: false,
    },
  },
  blog: {
    keywords: ['blog', 'articles'],
    url: {
      blog: false,
      articles: false,
    },
    dom: {
      list_of_articles: false,
      list_of_links: false,
    },
  },
  general: {
    forms_input: 0,
    videos_on_page: 0,
    content_on_page: 0,
  },
  misc: {
    has_sidebar: false,
    has_topbar: false,
    has_navbar: false,
  },
}
